package mge_data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.maiguoer.component.http.data.TopDataBase;
import com.maiguoer.component.http.data.User;

import mge_data.TopDataBaseDao;
import mge_data.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig topDataBaseDaoConfig;
    private final DaoConfig userDaoConfig;

    private final TopDataBaseDao topDataBaseDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        topDataBaseDaoConfig = daoConfigMap.get(TopDataBaseDao.class).clone();
        topDataBaseDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        topDataBaseDao = new TopDataBaseDao(topDataBaseDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(TopDataBase.class, topDataBaseDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        topDataBaseDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public TopDataBaseDao getTopDataBaseDao() {
        return topDataBaseDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
