package mge_data;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.maiguoer.component.http.data.TopDataBase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TOP_DATA_BASE".
*/
public class TopDataBaseDao extends AbstractDao<TopDataBase, Long> {

    public static final String TABLENAME = "TOP_DATA_BASE";

    /**
     * Properties of entity TopDataBase.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TagId = new Property(1, String.class, "tagId", false, "TopTagId");
        public final static Property TagTime = new Property(2, long.class, "tagTime", false, "TopTagId");
    }


    public TopDataBaseDao(DaoConfig config) {
        super(config);
    }
    
    public TopDataBaseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TOP_DATA_BASE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TopTagId\" TEXT," + // 1: tagId
                "\"TopTagId\" INTEGER NOT NULL );"); // 2: tagTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TOP_DATA_BASE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TopDataBase entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String tagId = entity.getTagId();
        if (tagId != null) {
            stmt.bindString(2, tagId);
        }
        stmt.bindLong(3, entity.getTagTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TopDataBase entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String tagId = entity.getTagId();
        if (tagId != null) {
            stmt.bindString(2, tagId);
        }
        stmt.bindLong(3, entity.getTagTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TopDataBase readEntity(Cursor cursor, int offset) {
        TopDataBase entity = new TopDataBase( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // tagId
            cursor.getLong(offset + 2) // tagTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TopDataBase entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTagId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTagTime(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TopDataBase entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TopDataBase entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TopDataBase entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
